In [1]:
# 1. 판다스와 넘파이를 임포트하기
import pandas as pd
import numpy as np

In [2]:
# 2. 판다스 버전 체크하기
pd.__version__

'1.2.4'

In [3]:
# 3. 판다스 라이브러리 버전 정보 모두 출력하기

In [4]:
# 4. 주어진 값으로 DataFrame 객체를 생성하시오

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

In [5]:
# 5. 객체내부 정보를 출력하시오
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [6]:
# 6. 객체 상위 3열까지 출력하시오
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [7]:
# 7. animal과 age 컬럼만 출력하시오
df.loc[:, 'animal':'age']

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [8]:
#8. 객체의 3, 4, 8번열에 해당하는 animal과 age 값만 출력 
df.loc[['c', 'd', 'h'], 'animal':'age']

  animal  age
c  snake  0.5
d    dog  NaN
h    cat  NaN

In [9]:
#9. visits 칼럼에서 3초과하는 값 출력

df[df['visits'] > 2]

  animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no

In [10]:
# 10. age 에서 NaN 값 출력
df[df['age'] == 'NaN' ]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

In [11]:
# 11. age가 3살 미만 고양이값 출력
df[(df['age'] < 3) & (df['animal'] == 'cat')]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

In [12]:
# 12. age가 2살이상 4살 미만인 값 출력
df[(df['age'] < 4) & (df['age'] >= 2)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

In [13]:
# 13. f 행의 나이를 1.5살로 변경
df.loc['f', 'age'] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [14]:
# 14. 객체에서 visit 의 합 출력
df['visits'].sum()

19

In [15]:
# 15. 동물별로 나이의 평균 출력
df.groupby('animal')['age'].mean()

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

In [16]:
# 16. k행을 추가하여 dog , 5.5세, 우선권없음(no), 방문회수 2회 열을 추가
df.loc['k'] = ['dog', 5.5, 2, 'no' ]
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no
k    dog  5.5       2       no

In [17]:
# 17. 객체에 있는 동물의 종류의 수 출력
df['animal'].nunique()

3

In [18]:
# 18. age 는 내림차순, visits 는 오름차순으로 정렬
df.sort_values('age', ascending=False)

  animal  age  visits priority
i    dog  7.0       2       no
k    dog  5.5       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
b    cat  3.0       3      yes
j    dog  3.0       1       no
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [19]:
df.sort_values('visits')

  animal  age  visits priority
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
k    dog  5.5       2       no
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  1.5       3       no

In [18]:
# 19. priority 의 yes를 True, no 를 False  로 맵핑 후 출력
map = {'yes': True, 'no': False}
df['priority'] = df['priority'].map(map)
df

  animal  age  visits  priority
a    cat  2.5       1      True
b    cat  3.0       3      True
c  snake  0.5       2     False
d    dog  NaN       3      True
e    dog  5.0       2     False
f    cat  2.0       3     False
g  snake  4.5       1     False
h    cat  NaN       1      True
i    dog  7.0       2     False
j    dog  3.0       1     False
k    dog  5.5       2     False

In [19]:
# 20. snake 를 python 으로 값을 변경
df['animal'] = df['animal'].replace('snake', 'python')
df

   animal  age  visits  priority
a     cat  2.5       1      True
b     cat  3.0       3      True
c  python  0.5       2     False
d     dog  NaN       3      True
e     dog  5.0       2     False
f     cat  2.0       3     False
g  python  4.5       1     False
h     cat  NaN       1      True
i     dog  7.0       2     False
j     dog  3.0       1     False
k     dog  5.5       2     False

In [21]:
# 21. 각각의 동물 유형과 방문 횟수에 대해, 평균나이를 찾으시오. 
# 즉,각 행은 animal 이고, 각 열은 visit 이며, 값은 평균연령
# (힌트, 피벗 테이블을 활용해야 함)
df = df.pivot_table(index='animal', columns='visits', values='age', aggfunc='mean')
df

visits    1         2    3
animal
cat     2.5       NaN  2.5
dog     3.0  5.833333  NaN
python  4.5  0.500000  NaN

In [26]:
# 22. 다음 객체에서 키값 A와 중복된 값이 제거된 1,2,3,4,5,6,7 이 출려되는 코드를 작성
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df['A'].unique()

array([1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [ ]:
# 23. 다음 객체에서 행의 각 요소에서 행의 평균을 뺀 값을 출력
df = pd.DataFrame(np.random.random(size=(5, 3)))