In [15]:
import pandas as pd
import random
import string
import numpy as np

In [16]:
def id():
    return ''.join(random.choice(string.ascii_letters) for i in range(5))

In [17]:
def score():
    return np.random.randint(0,100)

In [18]:
df = pd.DataFrame([[score() for i in range(1,6)] for i in range(1,11)], index=[id() for i in range(1,11)], columns=['국어', '영어', '수학', '과학', '사회'])

In [19]:
print(df)

       국어  영어  수학  과학  사회
kRkSr  50   7  17  13  78
lWITh  10   1  12  80  42
ctMXK  59  76  96  20   6
PGmpI  72   6  56   3   1
OetXi  79  62  31  50  11
YktKg  79  54  52  96   7
ZAGrc  90   2  59  52  76
ukVkD  80   9  36  39  34
byoaO  28  44  43  65  57
SFJHO  65   9  98  30  75

In [21]:
df.loc[['kRkSr'], '국어':'영어']

       국어  영어
kRkSr  50   7

In [22]:
df.iloc[[0], :]

       국어  영어  수학  과학  사회
kRkSr  50   7  17  13  78

In [23]:
#기술이 추가되었습니다 기존 학생들에게 랜덤으로 추가하시오

In [24]:
df.loc[:, '기술'] = pd.Series([score() for i in range(1,11)], index=df.index)  
df

       국어  영어  수학  과학  사회  기술
kRkSr  50   7  17  13  78  65
lWITh  10   1  12  80  42  82
ctMXK  59  76  96  20   6  44
PGmpI  72   6  56   3   1   6
OetXi  79  62  31  50  11  47
YktKg  79  54  52  96   7  90
ZAGrc  90   2  59  52  76  68
ukVkD  80   9  36  39  34   4
byoaO  28  44  43  65  57  58
SFJHO  65   9  98  30  75  45

In [25]:
# 각 학생들의 점수의 총합을 표현하는 컬럼을 추가하세요

In [26]:
df['총합'] = df.sum(axis=1)
df

       국어  영어  수학  과학  사회  기술   총합
kRkSr  50   7  17  13  78  65  230
lWITh  10   1  12  80  42  82  227
ctMXK  59  76  96  20   6  44  301
PGmpI  72   6  56   3   1   6  144
OetXi  79  62  31  50  11  47  280
YktKg  79  54  52  96   7  90  378
ZAGrc  90   2  59  52  76  68  347
ukVkD  80   9  36  39  34   4  202
byoaO  28  44  43  65  57  58  295
SFJHO  65   9  98  30  75  45  322

In [27]:
df.loc['총점'] = [df['국어'].sum(), df['영어'].sum(), df['수학'].sum(), df['과학'].sum(), df['사회'].sum(), df['기술'].sum(), df['총합'].sum()]
df

        국어   영어   수학   과학   사회   기술    총합
kRkSr   50    7   17   13   78   65   230
lWITh   10    1   12   80   42   82   227
ctMXK   59   76   96   20    6   44   301
PGmpI   72    6   56    3    1    6   144
OetXi   79   62   31   50   11   47   280
YktKg   79   54   52   96    7   90   378
ZAGrc   90    2   59   52   76   68   347
ukVkD   80    9   36   39   34    4   202
byoaO   28   44   43   65   57   58   295
SFJHO   65    9   98   30   75   45   322
총점     612  270  500  448  387  509  2726

In [28]:
df.sort_values('총합')

        국어   영어   수학   과학   사회   기술    총합
PGmpI   72    6   56    3    1    6   144
ukVkD   80    9   36   39   34    4   202
lWITh   10    1   12   80   42   82   227
kRkSr   50    7   17   13   78   65   230
OetXi   79   62   31   50   11   47   280
byoaO   28   44   43   65   57   58   295
ctMXK   59   76   96   20    6   44   301
SFJHO   65    9   98   30   75   45   322
ZAGrc   90    2   59   52   76   68   347
YktKg   79   54   52   96    7   90   378
총점     612  270  500  448  387  509  2726

In [29]:
df.sort_values('총합', ascending=False)

        국어   영어   수학   과학   사회   기술    총합
총점     612  270  500  448  387  509  2726
YktKg   79   54   52   96    7   90   378
ZAGrc   90    2   59   52   76   68   347
SFJHO   65    9   98   30   75   45   322
ctMXK   59   76   96   20    6   44   301
byoaO   28   44   43   65   57   58   295
OetXi   79   62   31   50   11   47   280
kRkSr   50    7   17   13   78   65   230
lWITh   10    1   12   80   42   82   227
ukVkD   80    9   36   39   34    4   202
PGmpI   72    6   56    3    1    6   144

In [35]:
df.drop('총점', inplace=True)
df.sort_values('총합')

KeyError: "['총점'] not found in axis"